### ISSUE TITLE
Custom Advancements

### ISSUE THREAD

**Issue by ImYepee** [SinmisModdingCommunity/The_Createville_Server#41] opened 2023-03-24 13:17 UTC
Just adding custom advancements which FTB has a mod u can do this with which would help with mod progression / help people start with some mods they wouldnt of tried before :)

**Comment by SinmisModdingCommunity** [comment] 2023-03-28 19:04
Duplicate of Custom Quests

**Closed as completed by SinmisModdingCommunity** 2023-03-28 19:05 UTC
Labels: enhancement
